# dein_lazy.toml
# ---------------------------
#
[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim', 'nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000

  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
  \ neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = ['snippet']
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)

  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
  let g:neosnippet#snippets_directory = '~/.vim/snippets/,~/.vim/bundle/snipmate/snippets/'
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
on_event = 'BufRead'
hook_add = '''
  nmap <silent> <C-r><C-t> :<C-u>Denite filetype<CR>
  nmap <silent> <C-r><C-p> :<C-u>Denite file_rec<CR>
  nmap <silent> <C-r><C-l> :<C-u>Denite line<CR>
  nmap <silent> <C-r><C-g> :<C-u>Denite grep<CR>
  nmap <silent> <C-r><C-]> :<C-u>DeniteCursorWord grep<CR>
  nmap <silent> <C-r><C-u> :<C-u>Denite file_mru<CR>
  nmap <silent> <C-r><C-y> :<C-u>Denite neoyank<CR>
  nmap <silent> <C-r><C-r> :<C-u>Denite -resume<CR>
  nmap <silent> <C-r>; :<C-u>Denite -resume -immediately -select=+1<CR>
  nmap <silent> <C-r>- :<C-u>Denite -resume -immediately -select=-1<CR>
'''

[[plugins]] # メソッドの定義元にジャンプ
repo = 'szw/vim-tags'
on_ft = ['ruby', 'perl', 'python', 'c', 'sh']

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby']
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

#[[plugins]]
#repo = 'kana/vim-operator-user'
#
#[[plugins]]
#repo = 'kana/vim-textobj-user'

#[[plugins]]
#repo = 'kana/vim-arpeggio'

#[[plugins]]
#repo = 'kana/vim-textobj-indent'

#[[plugins]]
#repo = 'rhysd/vim-operator-surround'
#depends = ['vim-operator-user']
#on_i = 1
#hook_source = '''
#  nmap <silent>sa <Plug>(operator-surround-append)
#  nmap <silent>sd <Plug>(operator-surround-delete)
#  nmap <silent>sr <Plug>(operator-surround-replace)
#'''

#[[plugins]]
#repo = 'emonkak/vim-operator-comment'
#depends = ['vim-operator-user', 'vim-textobj-user', 'vim-arpeggio', 'vim-textobj-indent']
#on_i = 1
#hook_source = '''
#  nmap tc  <Plug>(operator-comment)
#  nmap td  <Plug>(operator-uncomment)
#'''

# https://github.com/zchee/deoplete-jedi Neovimじゃないと不要？？
#[[plugins]]
#repo = 'neovim/python-client'

[[plugins]]
repo = 'zchee/deoplete-jedi'
#depends = ['python-client']
on_ft = ['python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

## [[plugins]]
## repo = 'vim-syntastic/syntastic'
## on_ft = ['python']
## hook_add = '''
##   let g:syntastic_always_populate_loc_list = 1
##   let g:syntastic_check_on_open = 1
##   let g:syntastic_check_on_wq = 0
##   " for Python
##   let g:syntastic_python_checkers = ['python', 'flake8', 'mypy']
## '''


