# dein_lazy.toml

# ------------- for JSON
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_source = '''
  let g:vim_json_syntax_conceal = 0
'''

# ------------- for JavaScript
[[plugins]] # ES6のハイライト
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# ------------- for python
[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['vim-virtualenv', 'deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'w0rp/ale'
depends = ['vim-virtualenv'] # 念のためおまじない
on_ft = ['python']
hook_source = '''
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_text_changed = 0

  let g:ale_sign_error = '✗'
  let g:ale_sign_error = '⚠'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

  let g:ale_sign_column_always = 1
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 0
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0

  let g:ale_linters = {
  \ 'python': ['flake8'],
  \}
  nmap [ale] <Nop>
  map <C-k> [ale]
  nmap <silent> [ale]<C-P> <Plug>(ale_previous)
  nmap <silent> [ale]<C-N> <Plug>(ale_next)
'''

# ------------- for perl
[[plugins]]
repo = 'c9s/perlomni.vim'
on_ft = ['perl']
#build = 'make'

# ------------- for typescript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

